import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :maria, MariaWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  url: [
    host: System.get_env("PHX_HOST")
  ],
  check_origin: [
    "https://#{System.get_env("PHX_HOST")}",
    "//*.#{System.get_env("PHX_HOST")}"
  ]

config :maria, MariaWeb.File,
  s3: [
    bucket: "gigalixir-maria"
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Maria.Finch

# Do not print debug messages in production
config :logger, level: :info


# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
